import Vue from 'vue';

import './styles/quasar.scss';
import '@quasar/extras/roboto-font/roboto-font.css';
import '@quasar/extras/material-icons/material-icons.css';
//import '@quasar/extras/material-icons-outlined/material-icons-outlined.css';
//import '@quasar/extras/material-icons-round/material-icons-round.css';
//import '@quasar/extras/material-icons-sharp/material-icons-sharp.css';
//import '@quasar/extras/fontawesome-v5/fontawesome-v5.css';
//import '@quasar/extras/ionicons-v4/ionicons-v4.css';
//import '@quasar/extras/mdi-v4/mdi-v4.css';
import '@quasar/extras/mdi-v5/mdi-v5.css';

import {
  Quasar,
  Ripple,
  ClosePopup,
  TouchPan,
  LoadingBar,
  Notify,
  Dialog,
  QLayout,
  QHeader,
  QDrawer,
  QPageContainer,
  QPage,
  QPageSticky,
  QToolbar,
  QToolbarTitle,
  QBtn,
  QBtnDropdown,
  QBtnGroup,
  QIcon,
  QList,
  QItem,
  QItemSection,
  QItemLabel,
  QSplitter,
  QScrollArea,
  QExpansionItem,
  QAvatar,
  QBtnToggle,
  QSeparator,
  QTooltip,
  QTable,
  QTd,
  QTh,
  QTr,
  QCard,
  QCardSection,
  QCardActions,
  QSelect,
  QToggle,
  QBadge,
  QSpace,
  QInput,
  QTabs,
  QTab,
  QTabPanels,
  QTabPanel,
  QDate,
  QTime,
  QPopupProxy,
  QBar,
  QPopupEdit,
  QRadio,
  QResizeObserver,
  QChip,
  QCheckbox,
  QPagination,
  QDialog,
  QVirtualScroll,
  QSkeleton,
  QImg,
  QMenu,
  QBanner
} from 'quasar';

Vue.use(Quasar, {
  config: {},
  components: {
    QLayout,
    QHeader,
    QDrawer,
    QPageContainer,
    QPage,
    QPageSticky,
    QToolbar,
    QToolbarTitle,
    QBtn,
    QBtnDropdown,
    QBtnGroup,
    QIcon,
    QList,
    QItem,
    QItemSection,
    QItemLabel,
    QSplitter,
    QScrollArea,
    QExpansionItem,
    QAvatar,
    QBtnToggle,
    QSeparator,
    QTooltip,
    QTable,
    QTd,
    QTh,
    QTr,
    QCard,
    QCardSection,
    QCardActions,
    QSelect,
    QToggle,
    QBadge,
    QSpace,
    QInput,
    QTabs,
    QTab,
    QTabPanels,
    QTabPanel,
    QDate,
    QTime,
    QPopupProxy,
    QBar,
    QPopupEdit,
    QRadio,
    QResizeObserver,
    QChip,
    QCheckbox,
    QPagination,
    QDialog,
    QVirtualScroll,
    QSkeleton,
    QImg,
    QMenu,
    QBanner
  },
  directives: {
    Ripple,
    ClosePopup,
    TouchPan
  },
  plugins: {
    LoadingBar,
    Notify,
    Dialog
  }
});
